In [1]:
NAME = "B M Rauf"
ID = ""
SECTION = ""

# Part 1: Solving a linear system using inverse matrix - 1 Marks

We have a linear system

\begin{align}
&a_{11} x_1 + a_{12} x_2 +  \cdots  + a_{1n} x_n = b_1\\
&a_{21} x_1 + a_{22} x_2 +  \cdots + a_{2n} x_n = b_2\\
&\cdots\\
&a_{n1} x_1 + a_{n2} x_2 +  \cdots + a_{nn} x_n = b_n\\
\end{align}

It is convenient to express this system in the
matrix form

\begin{align}
Ax = b
\end{align}

where $A$ is an $n \times n$ square matrix with elements $a_{ij}$, and $x$, $b$ are $n \times 1$ vectors.

We have to keep in mind that this system will have a unique solution iff $A$ is non-singular, given by $x = A^{-1}b.$

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import sys
np.set_printoptions(precision=6, formatter={'all': lambda x: f'{x:f}'})

In [3]:
def get_result_by_inverse_matrix(A, b):
  # A and b are numpy arrays

  # first check if the A is non-singular matrix. We know that the determinant of
  # a non-singular matrix will be non-zero


  # YOUR CODE HERE
    det=np.linalg.det(A)
    if det==0:
      return 'Inverse not pssible'
    Ainv=np.linalg.inv(A)
    x=np.dot(Ainv,b)

  # # HINT:
  # You may find functions such as linalg.det(), linalg.inv, etc. of the numpy package useful

    return x

In [4]:
# Test case for the get_result_by_inverse_matrix(A, b) function.

data_A = np.array([[1, 2, 1], [1, -2, 2], [2, 12, -2]])
data_b = np.array([0, 4, 4])

test = get_result_by_inverse_matrix(data_A, data_b)
result = np.array([11, -2.5, -6])

print(test)
print(result)

[11.000000 -2.500000 -6.000000]
[11.000000 -2.500000 -6.000000]


# Part 2: Gaussian elimination - 1.5 Marks

Gaussian elimination uses elementary row operations to transform the system to upper triangular form $Ux = y$.

Elementary row operations include swapping rows and adding multiples of one rowto another.
They won’t change the solution $x$, but will change the matrix $A$ and the right-hand side $b$.

The upper triangular matrix, $𝑈$, is defined as

\begin{bmatrix}
u_{11} & u_{12} & \cdots & u_{1n}\\
0 & u_{22} & \cdots & u_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & \cdots & 0 & u_{nn}\\
\end{bmatrix}


**Algorithm of Gaussian elimination**

Let $A^{(1)}=A$ and $b^{(1)}=b$. Then for each k from 1 to $n-1$, compute a new matrix $A^{(k+1)}$ and right-hand side $b^{(k+1)}$ by the following procedure:


1.   Define the row multipliers

\begin{align}
m_{ij} = \frac{a_{ik}^{(k)}}{a_{kk}^{(k)}}, i=k+1,\cdot \cdot \cdot,n.
\end{align}
2.   Use these to remove the unknown $x_k$ from equations $k + 1$ to $n$, leaving

\begin{align}
a_{ij}^{(k+1)}=a_{ij}^{(k)}-m_{ik}a_{kj}^{(k)}, b_{i}^{(k+1)}=b_{i}^{(k)}-m_{ik}b_{k}^{(k)}, i,j=k+1,\cdot \cdot \cdot, n.
\end{align}

It is helpful to combine these matrices to form an Augmented matrix (matrix $𝑏$ is the fourth column). We will perform this row operations on the Augmented matrix. It takes care of both $𝐴$ and $𝑏$ matrixes at the same time.

After generating the upper triangular matrix, we have to apply **backward substitution method**.
For any $n \times n$ upper triangular system, $Ux = b$, the solution is:

\begin{align}
x_j = \frac{b_j-\sum_{k=j+1}^{n}u_{jk}x_k}{u_{jj}}, j = n, n-1, \cdot\cdot\cdot, 1.
\end{align}

Here we assumed that $det𝑈≠0$.


In [5]:
def get_result_gaussian_elimination(n, A):
    # n is the number of unknowns.
    # A is a numpy array representing the Augmented n x (n+1) matrix.
    x = np.zeros(n)
    # First check if the A is non-singular matrix.
    # The determinant of a non-singular matrix will be non-zero.
    # Return None if there is no unique solution to the linear equation.

    # YOUR CODE HERE
    # for i in range(n):
    #   for j in range(n):
    #     if i==j and A[i][j]==0:
    #       return 'Upper Triangular Matrix not possible.'

    # Check if the coefficient matrix is non-singular
    coeff = A[:, :-1]
    if abs(np.linalg.det(coeff))==0:
      return None

    # Forward elimination to form upper triangular matrix
    for i in range(n):
        # Pivoting (optional but good practice to avoid divide-by-zero or instability)
        if A[i][i] == 0:
            for j in range(i + 1, n):
                if A[j][i] != 0:
                    A[[i, j]] = A[[j, i]]
                    break

        for j in range(i + 1, n):
            mul = A[j][i] / A[i][i]
            for k in range(n + 1):
                A[j][k] -= mul * A[i][k]


    # Back substitution
    x[n - 1] = A[n - 1][n] / A[n - 1][n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = A[i][n]
        for j in range(i + 1, n):
            x[i] -= A[i][j] * x[j]
        x[i] /= A[i][i]

    # HINT:
    # Apply Gauss Elimination followed by Back Substitution
    return x

In [6]:
# Test case for the get_result_gaussian_elimination(n, A) function.

data_n = 3
data_A = np.array([[1, 2, 1, 0], [1, -2, 2, 4], [2, 12, -2, 4]])

test = get_result_gaussian_elimination(data_n, data_A)
result = np.array([11, -2.5, -6])

print(test)
print(result)

[11.000000 -2.500000 -6.000000]
[11.000000 -2.500000 -6.000000]


# Part 3: LU Decomposition - 1.5 Marks

We will transform the $n \times n$ matrix $A$ into a product of two triangular matrix: one lower triangular $(L)$ and the other upper triangular $(U)$.

\begin{align}
A = LU
\end{align}

**Algorithm of LU decomposition:**


1.   Initialize  $L$  to an identity matrix,  $I$  of dimension  $n×n$  and  $U=A$ .
2.   For  $i=1,…,n$  do Step $3$
3.   &nbsp;&nbsp; For  $j=i+1,…,n$  do Steps $4$-$5$
4.  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Set  $l_{ji}=u_{ji}/u_{ii}$
5. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Perform  $U_j=(U_j−l_{ji}U_i)$  (where  $U_i,U_j$  represent the  $i$  and  $j$  rows of the matrix  $U,$  respectively)

*   We know, The linear system in matrix form is $𝐴𝑥=𝑏$.
*   Using the decomposition, we get $𝐿𝑈𝑥=𝑏$.
*    Now, let $𝑈𝑥=𝑦⟹𝐿𝑦=𝑏$.
*   Since $𝐿$ is lower triangular, we solve $𝐿𝑦=𝑏$ to obtain $𝑦$ by forward substitution.
*   Since $𝑈$ and $𝑦$ are known, we solve $𝑈𝑥=𝑦$ to obtain $𝑥$ by backward substitution.

In [7]:
def lu(A):
    # Get the number of rows
    n = A.shape[0]

    U = A.copy().astype(np.double)
    L = np.eye(n, dtype=np.double)

    # YOUR CODE HERE
    for i in range(n):
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ZeroDivisionError("Division by zero detected in LU decomposition.")
            factor = U[j, i] / U[i, i]
            U[j, :] -= factor * U[i, :]
            L[j, i] = factor

    # HINT:
    #Loop over rows
    # for i in range(n):
        #Eliminate entries below i with row operations
        #on U and reverse the row operations to
        #manipulate L

    return L, U

def forward_substitution(L, b):

    #Get number of rows
    n = L.shape[0]

    #Allocating space for the solution vector
    y = np.zeros_like(b, dtype=np.double);


    # YOUR CODE HERE
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])

    return y

    # HINT:
    #Perform the forward-substitution.
    #Initialize  with the first row.
    #Loop over rows in reverse (from the bottom  up),
    #Start with the second to last row, because  the
    #last row solve was completed in the last step.

    return y



def back_substitution(U, y):

    #Number of rows
    n = U.shape[0]

    #Allocating space for the solution vector
    x = np.zeros_like(y, dtype=np.double);


    # YOUR CODE HERE
    for i in range(n-1, -1, -1):
        if U[i, i] == 0:
            raise ZeroDivisionError("Zero pivot encountered during back substitution.")
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

    # HINT:
    #Perform the back-substitution.
    #Initialize with the last row.
    #Loop over rows in reverse (from the bottom up),
    #Start with the second to last row, because the
    #last row solve was completed in the last step.

    return x



def lu_solve(A, b):
    L, U = lu(A)
    y = forward_substitution(L, b)
    return back_substitution(U, y)

In [8]:
# Test case for the lu_solve(A, b) function.

data_A = np.array([[1., 2., 1.], [1., -2., 2.], [2., 12., -2.]])
data_b = np.array([0., 4., 4.])

test = lu_solve(data_A, data_b)
results = [11, -2.5, -6]

np.testing.assert_array_equal(test, results)
print(test)
print(result)

[11.000000 -2.500000 -6.000000]
[11.000000 -2.500000 -6.000000]


# Daily Evaluation - 4 Marks

In [9]:
'''
a + 2b + 3c + 4d + 5e = 55
- a + 3c + 5e = 33 - 2b - 4d
5e + 3c - 44 = -4b + a - 4d
- 3c + 5e - 22 = a -4d - 4b
3b - a = 11 - 2d

Find the solution of the above system of equations using the Gauss Elimination method. Generate and print :
1. The augmented matrix (a 2D numpy array).
2. The row multipliers (a 2D numpy array).
3. The resulting upper triangular matrix (a 2D numpy array).
4. The solutions (a 1D numpy array).
'''

# augmented matrix
A = np.array([
    [1,  2,  3,  4,  5],
    [-1, 2, 3, 4, 5],
    [-1,  4, 3, 4, 5],
    [-1, 4, -3, 4, 5],
    [-1, 3, 0, 2, 0]
], dtype=np.double)

b = np.array([55, 33, 44, 22, 11], dtype=np.double)

# 1. Augmented Matrix
augmented_matrix = np.hstack((A, b.reshape(-1, 1)))
print("1. Augmented Matrix:")
print(augmented_matrix)

def get_result_gaussian_elimination(n, A_aug):
    A = A_aug.copy()
    x = np.zeros(n)
    row_multipliers = np.zeros((n, n))

    # Check for singular matrix
    coeff = A[:, :-1]
    if np.abs(np.linalg.det(coeff)) < 1e-10:
        return None

    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if i != max_row:
            A[[i, max_row]] = A[[max_row, i]]

        for j in range(i+1, n):
            if A[i][i] == 0:
                continue
            multiplier = A[j][i] / A[i][i]
            row_multipliers[j][i] = multiplier
            A[j] = A[j] - multiplier * A[i]

    # Back substitution
    for i in range(n-1, -1, -1):
        x[i] = A[i][-1] - np.sum(A[i][i+1:n] * x[i+1:n])
        x[i] /= A[i][i]

    return A, row_multipliers, x

n = 5
upper_triangular_matrix, row_multipliers, solution = get_result_gaussian_elimination(n, augmented_matrix)

print("\n2. Row Multipliers:")
print(row_multipliers)

print("\n3. Upper Triangular Matrix:")
print(upper_triangular_matrix)

print("\n4. Solution [a, b, c, d, e]:")
print(solution)

1. Augmented Matrix:
[[1.000000 2.000000 3.000000 4.000000 5.000000 55.000000]
 [-1.000000 2.000000 3.000000 4.000000 5.000000 33.000000]
 [-1.000000 4.000000 3.000000 4.000000 5.000000 44.000000]
 [-1.000000 4.000000 -3.000000 4.000000 5.000000 22.000000]
 [-1.000000 3.000000 0.000000 2.000000 0.000000 11.000000]]

2. Row Multipliers:
[[0.000000 0.000000 0.000000 0.000000 0.000000]
 [-1.000000 0.000000 0.000000 0.000000 0.000000]
 [-1.000000 0.666667 0.000000 0.000000 0.000000]
 [-1.000000 1.000000 -0.333333 0.000000 0.000000]
 [-1.000000 0.833333 0.333333 -0.250000 0.000000]]

3. Upper Triangular Matrix:
[[1.000000 2.000000 3.000000 4.000000 5.000000 55.000000]
 [0.000000 6.000000 6.000000 8.000000 10.000000 99.000000]
 [0.000000 0.000000 -6.000000 0.000000 0.000000 -22.000000]
 [0.000000 0.000000 0.000000 2.666667 3.333333 14.666667]
 [0.000000 0.000000 0.000000 -0.000000 -2.500000 -5.500000]]

4. Solution [a, b, c, d, e]:
[11.000000 5.500000 3.666667 2.750000 2.200000]
